### ISSUE TITLE
Ручка восстановления промокода

### ISSUE THREAD

**Issue by T1rax** [T1rax/movies_loyalty_program#10]
Восстановить промокод
PATCH: /promo/{promo}/use
Вызывается если не прошла оплата промика.

Parameters
- user_id - кому восстанавливаем промокод

**Comment by T1rax** [comment]
Применение наоборот
Минусовать примненеия и апдейтнуть флаг

**Comment by wiky-avis** [comment]
Восстановить промокод
POST: /promos/restore
Вызывается если не прошла оплата промика.

Body:
- user_id(optional) - кому восстанавливаем промокод
- promo_code - промокод
