### ISSUE TITLE
Ручка деактивации промокодов

### ISSUE THREAD

**Issue by T1rax** [T1rax/movies_loyalty_program#11]
Деактивировать промокод
POST: /promo/{promo}/deactivate
Сделать так, чтобы больше не работал, но не удалять по-настоящему

**Comment by T1rax** [comment]
Меняем статус флага

**Comment by wiky-avis** [comment]
Деактивировать промокод
POST: /promos/deactivate
Сделать так, чтобы больше не работал, но не удалять по-настоящему

Body:
- user_id(optional) - кому деактивируем промокод
- promo_code - промокод
