### ISSUE TITLE
Ручка получения статуса промокодов

### ISSUE THREAD

**Issue by T1rax** [T1rax/movies_loyalty_program#8]
Узнать статус промокода
POST: /promo/status

Parameters
- user_id - кому активируем
- promo - сам промокод

**Comment by wiky-avis** [comment]
навесить рейтлимит на ручку

**Comment by wiky-avis** [comment]
Узнать статус промокода
POST: /promos/status

Body:
- user_id(optional) - кому активируем (из токена)
- promo_code - сам промокод (body)
